### ISSUE TITLE
données intégrées au package

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/DoReMIFaSol#24]
J'ai une petite interrogation sur les données figurant en dur dans le package. Le README ne mentionne pas leur existence.

Sont-elles là uniquement en tant qu'exemples de ce que produisent les fonctions de téléchargement ?
Ou bien surtout pour éviter de retélécharger plusieurs fois ? D'ailleurs que se passera-t-il quand ces données auront un millésime plus récent ? J'imagine que l'idée n'est pas d'accumuler les jeux de données, faute de quoi la taille du package va enfler.

**Comment by pierre-lamarche** [comment]
Alors en vérité l'existence des données intégrées dans le package est le résultat d'une concession accordée à certains membres d'UtilitR, qui voulaient s'en servir pour la reproductibilité des codes exhibés dans la documentation. Un des pré-requis était que le code tourne aussi sur AUS, et comme tu t'en doutes, `doremifasol` n'a aucun sens sous AUS sans connexion Internet. Donc pour pouvoir accéder aux exigences d'un certain Olivier, j'ai intégré quelques jeux de données. Mais ce n'est pas le but du package, et hormis cet aménagement avec les besoins d'UtilitR, cela n'a pas vraiment de sens.

De mon point de vue, ces données ont vocation à disparaître du package.

**Comment by py-b** [comment]
Merci, je comprends mieux !

**Comment by py-b** [comment]
Une solution ne serait-elle pas de créer un package dédié (`doremifasoldata`?) pour stocker ces données ?
Cela pourrait contenter les membres d'utilitR tout en allégeant considérablement le package et en le recentrant sur sa fonction principale.

**Comment by py-b** [comment]
(j'invoque @oliviermeslin et @linogaliana 🧙 )

**Comment by linogaliana** [comment]
@pierre-lamarche maintenant le package `doremifasol`, c'est lui qui fixe les orientations du package, nous on s'adapte. Côté `utilitR`, l'accès à une base sans connexion internet apparaît en effet nécessaire pour avoir des exemples reproductibles. Mais cela peut très bien passer par un package annexe `doremifasol-data`, plus figé que `doremifasol`, comme le propose @py-b .

D'ailleurs, il faudra qu'on discute d'un *post* sur www.utilitr.org pour faire la promo de `doremifasol` (ou `doremifasol-data`) et expliquer les principales vertus du :package: J'ouvrirai une issue spécifique sur le sujet dans ce dépôt

**Comment by pierre-lamarche** [comment]
Pour moi c'est une excellente idée @py-b . Dont acte, j'ai créé un package `doremifasolData` accueillant les données pour `utilitR`.
Et du coup c'est très propre, on a un `check` sur `doremifasol` avec que du vert.

**Comment by oliviermeslin** [comment]
C'est effectivement une excellente idée, merci @py-b de l'avoir suggéré. J'ai toutefois une suggestion importante: il me semble très souhaitable que le package de données associé à `utilitR` porte un nom qui rappelle immédiatement le nom de la documentation. J'ai pensé à `utilitRdata`, mais on peut sûrement trouver autre chose. Ca permet par ailleurs de bien séparer les objectifs d'`utilitR` (former les agents) et de `doremifasol` (faciliter l'accès aux données de l'Insee).

@linogaliana , @pierre-lamarche : ça vous irait?

**Comment by pierre-lamarche** [comment]
@oliviermeslin je suis un peu partagé par cette proposition, puisque les données insérées dans le `package` vont l'être à partir de `doremifasol`. Je voyais tout de même `doremifasol` comme un outil pour faciliter le _dogfooding_ en interne, si cher à certains d'entre nous ; de ce point de vue, je trouve dommage de séparer aussi fortement `utilitR` et `doremifasol`.

**Comment by linogaliana** [comment]
> 
> 
> Pour moi c'est une excellente idée @py-b . Dont acte, j'ai créé un package `doremifasolData` accueillant les données pour `utilitR`.
> Et du coup c'est très propre, on a un `check` sur `doremifasol` avec que du vert.

Merci @pierre-lamarche . J'ouvre une *issue* dans `utilitR` pour remplacer les appels à `doremifasol` par `doremifasol-data`

**Comment by py-b** [comment]
@linogaliana : si ça peux t'aider, j'ai déjà fait un PR pour la déclaration dans DESCRIPTION : https://gitlab.com/linogaliana/documentationR/-/merge_requests/65

Je crois que les tirets sont interdits dans les noms de packages (d'où le nom `doremifasolData` choisi par Pierre).
