### ISSUE TITLE
encodage en générant liste_donnees

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/DoReMIFaSol#28]
En écrivant des tests unitaires pour `liste_donnees`, j'ai détecté une anomalie ligne 1292 (valeur manquante pour `$api_rest`).

J'ai donc modifié le csv et relancé `data-raw/liste_donnees.R`. Le problème est que l'encodage des caractères accentués n'est plus bon dans les rda générés.

J'ai raté un truc, @pierre-lamarche ?

**Comment by pierre-lamarche** [comment]
Sous quel OS travailles-tu pour `doremifasol` ?
L'encodage du fichier csv est UTF-8 ; d'expérience, si tu ouvres le fichier avec LibreOffice sous Windows, le système te fait des petites blagues en modifiant l'encodage du fichier (il le passe en CP1252). Du coup, ça plante puisqu'on spécifie l'encodage dans la ligne d'import du csv (fichier `liste_donnees.R` dans le dossier `raw-data`, ligne 5). Il faut bien spécifier le format d'encodage quand on sauvegarde le csv après modification.

**Comment by py-b** [comment]
Windows 8 sur mon poste perso et Windows 10 sur poste Insee.

Je n'ai pas fait l'erreur d'essayer de le modifier avec LibreOffice ! Dans un premier temps, j'ai modifié le csv dans RStudio directement, puis avec NotePad++ qui m'a indiqué que c'était bien en UTF-8 avant et après la modif.

Mystérieux et toujours pénibles ces problèmes d'encodage...

**Comment by py-b** [comment]
Probablement plus d'actualité avec le passage au json.
