### ISSUE TITLE
Activer l'accès à Travis CI et à codecov.io pour les badges

### ISSUE THREAD

**Issue by pierre-lamarche** [InseeFrLab/DoReMIFaSol#29]
Un code coverage à 57 % c'est moche et surtout faux !
Potentiellement j'aurais besoin de l'intervention d'un admin de InseeFrLab, c'est pour cette raison que je te rajoute @olevitt .

**Comment by olevitt** [comment]
Hello !

De ce que je vois, travis tourne bien sur le projet.
Tu as besoin de quoi comme réglage sur travis ?
Normalement les droits de travis sont liés aux droits de github.

**Comment by py-b** [comment]
Si on lance :
```r
pc <- covr::package_coverage()
pc
#> doremifasol Coverage: 57.07%
#> R/telechargerFichier.R: 46.67%
#> R/chargerDonnnees.R: 52.08%
#> R/millesimesDisponibles.R: 83.33%
#> R/utile.R: 95.65%
#> R/consulter.R: 100.00%
#> R/telechargerDonnees.R: 100.00%
```
On obtient bien 57,07 %

En analysant plus finement avec `covr::report(pc)`, on s'aperçoit que toute la partie "API/token/json" ne fait l'objet d'aucun test, ce qui explique ce faible pourcentage de lignes parcourues par les tests.

**Comment by pierre-lamarche** [comment]
Merci @py-b , avant j'avais un taux de république bananière à 96 %. C'est étrange, je vais investiguer.

**Comment by pierre-lamarche** [comment]
J'obtiens cela chez moi : 

``` r
pc <- covr::package_coverage()
#> Error: '/tmp/RtmpYwL6bP/reprex42e15f1fbf77' does not contain a package!
pc
#> Error in eval(expr, envir, enclos): objet 'pc' introuvable
#> doremifasol Coverage: 97.07%
#> R/millesimesDisponibles.R: 83.33%
#> R/utile.R: 95.65%
#> R/chargerDonnnees.R: 96.88%
#> R/telechargerFichier.R: 98.67%
#> R/consulter.R: 100.00%
#> R/telechargerDonnees.R: 100.00%
```
En fait c'est un problème de jeton pour accéder à l'API, avec la migration du dépôt il n'y a plus de jeton pour accéder à l'API de l'Insee.

**Comment by pierre-lamarche** [comment]
Bon on est de retour à 97 % en réalisant en local l'analyse de code coverage et en rebalaçant le résultat du codecov.io.
Il me reste à valider l'autorisation de Travis dans InseeFrLab, mais on n'en est plus très loin.

**Comment by pierre-lamarche** [comment]
@olevitt il me semble que c'est toi qui valide les demandes ; tu as accepté l'accès de codecov.io au dépôt, mais pas celui de Travis (si je ne me trompe pas). Du coup, y a-t-il une objection à cet accès ?

**Comment by olevitt** [comment]
Sorry j'ai pas suivi, il vous manque quoi ?  
J'ai l'impression que les builds tournent bien, non ?https://travis-ci.org/github/InseeFrLab/DoReMIFaSol

**Comment by pierre-lamarche** [comment]
En fait le badge pointe vers ce lien : https://travis-ci.com/inseeFrLab/doremifasol
Du coup je vais modifier les liens et voir si ça résout le souci sur codecov.io.

**Comment by olevitt** [comment]
C'est l'arnaque classique de travis. Travis-ci.org c'est pour les projets opensource, travis-ci.com c'est l'offre entreprise payante (projets privés). Donc oui, il faut que tout soit en org

**Comment by pierre-lamarche** [comment]
Parfait, j'ai accès aux variables d'environnement du build sur le domaine .org donc j'ai pu rajouter les jetons pour l'accès à l'API. Ça doit marcher maintenant. Merci beaucoup !
