### ISSUE TITLE
re-téléchargement des fichiers

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/DoReMIFaSol#32]
Pour éviter que les données soient re-téléchargées inutilement, le package regarde actuellement si un fichier portant le même nom existe dans `telDir`.

Pour peaufiner un peu le truc, j'ai deux idées (pas forcément incompatibles) : 

- ajouter un paramètre `force` (`=FALSE` par défaut), qui permette à l'utilisateur de télécharger quand même ;
- s'assurer de l'intégrité du fichier avec une vérification par somme de contrôle. Pour cela, il faudrait stocker dans `liste_donnees` les hash correspondant aux fichiers dispo sur insee.fr. On s'assure que le fichier n'a pas été altéré par l'utilisateur entre le 1er et le 2e téléchargement, mais pas que le fichier sur insee.fr n'a pas changé !

J'ai testé le calcul d'une somme de contrôle sur le fichier _RP2016_LOGEMT_csv.zip_ (380 Mo) avec [tools::md5sum](https://stat.ethz.ch/R-manual/R-devel/library/tools/html/md5sum.html). C'est quasi-instantané. La difficulté est plutôt de précalculer les hash qu'on va stocker dans `liste_donnees`. Il faudrait télécharger à nouveau tous les fichiers (ou les récupérer par un autre moyen...).

Un avis ? 🙂

**Comment by py-b** [comment]
> Il faudrait télécharger à nouveau tous les fichiers (ou les récupérer par un autre moyen...).

Il n'y a que 45 fichiers à télécharger, donc ce n'était pas la mer à boire :
https://gist.github.com/py-b/6bc3167068b8a3d1651140d9977375cd

**Comment by pierre-lamarche** [comment]
Ok impeccable, je vais créer une branche pour l'ajout de la colonne `md5sum` dans le fichier `liste_donnees.csv`.
Merci beaucoup, c'est une excellente idée !

**Comment by pierre-lamarche** [comment]
Voilà c'est intégré @py-b , dis-moi ce que tu en penses ! Et encore merci pour tes contributions, c'est vraiment cool !

**Comment by py-b** [comment]
Parfait !
J'ai ajouté l'idée du paramètre `force` (cf. #36).

De rien pour les contributions (j'ai d'autres idées mais j'essaie de ne pas te submerger sous les PR).
À propos, je pourrais avoir la possibilité d'écrire des branches dans le repo (plutôt que dans mon fork) ?

**Comment by pierre-lamarche** [comment]
Je vois les administrateurs de inseeFrLab demain, je leur demande de te rajouter dans l'équipe !
Merci encore !

**Comment by olevitt** [comment]
> Je vois les administrateurs de inseeFrLab demain, je leur demande de te rajouter dans l'équipe !
> Merci encore !

C'est fait, invitation envoyée :)

**Comment by py-b** [comment]
Merci @olevitt.
