### ISSUE TITLE
Stocker la liste des données en json et pas en csv

### ISSUE THREAD

**Issue by pierre-lamarche** [InseeFrLab/DoReMIFaSol#39]
En y réfléchissant, je me dis que ça aurait plus de sens de stocker la liste sur un format qui offrirait plus de flexibilité sur la structure, et donc sur le contenu des métadonnées qu'on pourrait y mettre. En particulier définition des noms de colonnes, de leur type plus facile.
Je vais créer une branche expérimentale en ce sens.

**Comment by py-b** [comment]
Ça me semble approprié.
Il faudra penser à bien documenter comment est structuré ce json et comment le modifier (probablement dans `CONTRIBUTING.md`).

_Sinon en regardant l'ébauche de json, je m'aperçois que la colonne `size` a été stockée en "character"._

**Comment by pierre-lamarche** [comment]
En effet, j'ai corrigé du coup sur la branche `json`.

**Comment by pierre-lamarche** [comment]
Sur la génération du json, j'envisage de toujours repartir du csv et de scripter son enrichissement, de manière à ce que les contributeurs puissent éditer un csv plutôt qu'un json. Qu'en penses-tu ?

**Comment by py-b** [comment]
Ce serait le plus simple, mais comment rentrer les informations du genre nom et type des colonnes dans le csv ?

Par exemple, `telechargerDonnees("COG_COMMUNE", 2018)` produit une table ou la colonne `REG` est importée en tant que nombre par `readr`.

C'est de ce genre de problème dont parlais en disant _"En particulier définition des noms de colonnes, de leur type plus facile"_ ou j'ai mal compris ?

**Comment by pierre-lamarche** [comment]
Tout à fait, ça permettrait de générer des `col_types` sous forme de listes de manière très naturelle, puisque c'est la structure de données qui correspond à du json en R.

**Comment by py-b** [comment]
Mais comment saisir de manière simple cette information dans le csv ?

Par ailleurs, le fait de conserver le csv (+ script associé) implique une contrainte sur la structure, alors qu'on voulait gagner en flexibilité.

**Comment by pierre-lamarche** [comment]
Disons que ce n'est pas le contributeur qui fait l'effort d'enrichissement, plutôt le mainteneur. Donc on ne saisit pas l'info dans le CSV (sinon on garderait ce format). Ce n'est qu'au moment d'accepter la PR que le mainteneur déterminera la nature des variables (mais par exemple sur les données RP, c'est assez simple puisqu'il peut dériver cette information des méta-données).

**Comment by py-b** [comment]
Ok, c'est un bon compromis.
Par contre prudence, car dans l'état actuel de la branche, l'appel à `jsonlite::toJSON(liste_donnees)` écrase les infos précédemment rentrées à la main par le mainteneur.

**Comment by pierre-lamarche** [comment]
Pour l'instant, c'est du brouillon (on continue de partir du csv originel pour générer le json).
Pour le futur, on aura un workflow pour gérer les contributions :
1. Mise à jour du csv par le contributeur
2. Une routine se charge d'incorporer la (les) nouvelle(s) entrée(s) dans le json
3. De manière plus ou moins ad hoc, le mainteneur incorpore les métadonnées associées à la (les) nouvelle(s) entrée(s).

Donc coexistence du csv et du json, mais c'est ce dernier qui fait foi. En effet, on autorisera le fait qu'une donnée soit recensée dans le json mais pas dans le csv (ce dernier sert uniquement à alimenter le json).

**Comment by RLesur** [comment]
Ce qui a été fait sur le json est super intéressant. Ca me rappelle en partie [Table Schema](https://specs.frictionlessdata.io/table-schema/).

**Comment by py-b** [comment]
J'ai de plus en plus l'impression qu'on pourrait se passer totalement du csv.

Outre le fait que le json offre plus de possibilités pour charger proprement les données, je trouve qu'il présente aussi l'avantage d'être plus facile à alimenter par un contributeur.

Par exemple :
```json
{
    "nom": "RP_ACTRES_IRIS",
    "libelle": "Données du Recensement de Population, données sur les activités des résidents au niveau IRIS",
    "date_ref": "2017-01-01",
    "collection": "RP",
    "lien": "https://www.insee.fr/fr/statistiques/fichier/4799323/base-ic-activite-residents-2017.zip",
    "type": "xlsx",
    "zip": true,
    "big_zip": false,
    "fichier_donnees": "base-ic-activite-residents-2017.xlsx",
    "onglet": "IRIS",
    "premiere_ligne": 6
}
```
versus
```
RP_ACTRES_IRIS,"Données du Recensement de Population, données sur les activités des résidents au niveau IRIS",01/01/2017,RP,https://www.insee.fr/fr/statistiques/fichier/4799323/base-ic-activite-residents-2017.zip,xlsx,TRUE,FALSE,base-ic-activite-residents-2017.xlsx,,IRIS,6,,,,,FALSE,,
```

Cela permet de ne pas avoir à craindre d'oublier un champ ou de ne pas les renseigner dans l'ordre exact (ou de passer par un tableur avec de potentiel problèmes d'encodage, de séparateur...).

Il y a juste à documenter dans `CONTRIBUTING.md` la syntaxe générale et les champs absolument nécessaires.

**Comment by pierre-lamarche** [comment]
Dont acte. J'effectue le passage dès que j'ai un peu de temps.

**Comment by py-b** [comment]
Ok ! De mon côté, je commence à réfléchir sur le CONTRIBUTING.md (en fait j'y ai déjà réfléchi un peu).

**Comment by py-b** [comment]
Bonjour @jdlom. Merci pour ton intérêt pour le package !

L'utilisation du json est effective. Si tu souhaites proposer une source de données, tu peux ouvrir une _issue_ (il y a un modèle qui te guidera).

Les infos à fournir ne sont pas très nombreuses, notamment pas besoin du md5.

**Comment by py-b** [comment]
@pierre-lamarche : on peut fermer cette _issue_ ?

**Comment by pierre-lamarche** [comment]
Oui, il faudrait néanmoins fusionner la branche `json` avec le `master` ; j'ai perdu de vue pourquoi je ne l'ai pas fait plus tôt, je vérifie et je clos.

**Comment by pierre-lamarche** [comment]
Le commit [07de50c](https://github.com/InseeFrLab/DoReMIFaSol/commit/07de50cd849de00a44c8a2353c6fefac88d4287f) clôt l'exercice. Le `json` est désormais le fichier de référence unique - je laisse le csv par acquit de conscience, mais on pourra le bazarder prochainement.
