### ISSUE TITLE
Warning "L'extension du fichier diffère du type de fichier."

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/DoReMIFaSol#41]
https://github.com/InseeFrLab/DoReMIFaSol/blob/63f9754f145f0a4741c69480f0fadacbbafa408b/R/chargerDonnnees.R#L42-L44

Ce warning est déclenché par exemple par `telechargerDonnees("COG_COMMUNE", 2018)`.

À quoi sert-il, vu que les traitements suivants sont les mêmes que si l'extension ne différait pas et que la résultat est bien celui attendu ?

**Comment by pierre-lamarche** [comment]
Dans le cas du COG 2018, effectivement le fichier est un `.txt`, là où habituellement ce sont plutôt des `.csv` qui sont attendus. Initialement l'avertissement s'adressait en vérité plutôt à l'auteur du package qu'aux utilisateurs, puisque comme tu le signales, pour eux c'est transparent.
Je n'aurais aucun scrupule à faire disparaître l'avertissement en effet.
