### ISSUE TITLE
Shapefiles issus de l'IGN

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/DoReMIFaSol#46]
Je me demandais si les shapefiles des limites adminstratives rentraient dans le périmètre de `doremifasol`.

Ils sont disponibles sur le site de l'ign [ici](https://geoservices.ign.fr/documentation/diffusion/telechargement-donnees-libres.html#les-bases-de-donn%C3%A9es-au-format-vectoriel) et peuvent être associés aux données de `doremifasol` via le code commune, par exemple.

Bref, doremifasol concerne-t-il exclusivement **insee.fr** ?

**Comment by py-b** [comment]
> Bref, doremifasol concerne-t-il exclusivement insee.fr ?

Réponse bête et méchante : oui, car le "mi" de `doremifasol` est pour "mise à disposition par l'Insee". :grin: 

Ce serait cool d'avoir un outil pour charger automatiquement un fonds de carte dans R, mais l'IGN n'est pas plus légitime pour diffuser ses propres données ? Ce sont des données sur lesquelles on a moins de maîtrise/visibilité et qui ne constituent pas notre coeur de métier. D'ailleurs, peut-être ont-ils déjà une API ou un outil type `doremifasol` ?

De plus, `doremifasol` vise non seulement à télécharger les fichiers mais surtout (?) à les charger dans R. Cela implique qu'il faudrait développer toute une partie import avec un certains nombres de dépendances supplémentaires (`sf`...).

En résumé, plutôt mitigé au premier abord.

**Comment by pierre-lamarche** [comment]
Alors sur le sujet IGN en particulier, le fonctionnement tel qu'on l'imagine sur `doremifasol` pose de nombreux défis, et pas seulement en termes de dépendances de packages, mais aussi de librairies système. En effet, les données cartographiques de l'IGN sont mises à disposition sous format compressé 7z (et pas zip) ce qui suppose que tu ne peux pas utiliser la fonction `unzip` habituelle une fois les données téléchargées. Pour cela il faut aller installer le package `archive` qui se trouve [ici](https://github.com/jimhester/archive), pas disponible sur le CRAN (mais ce n'est pas forcément un défaut ;-)).
Le problème c'est que pour installer le package `archive` il faut aussi installer des dépendances système (je pense que c'est la raison pour laquelle le développeur n'est pas allé sur le CRAN). J'ai d'ailleurs fait une [PR sur le rstudio de l'innovation pour avoir cette librairie système](https://github.com/InseeFrLab/rstudio/commit/fbb29ef2d9cc019354ab80a149127b3b3834090d).
Mais du coup le package ne peut pas tourner chez tout le monde (et en particulier pas sur les postes pro...). Il faut alors en passer par un système de docker, pourquoi pas mais on entre dans une autre dimension dans ce cas.
BTW il y a [ce package](https://github.com/antuki/CARTElette) qui est développé par une collègue et qui fait le job ; pas complètement fan sur le principe puisque précisément les fonds de carte sont déjà chargés dans le package (alors que moi je préfèrerais un système de téléchargement on-the-fly à la `doremifasol`, mais ça résout les soucis décrits ci-dessus).
Enfin je pense que ça ouvre une autre question - mais ça je le réserve pour plus tard : a-t-on envie d'étendre le champ de `doremifasol` à l'ensemble des données du SSP ? Pour l'instant, je suis assez en phase avec ce que dit @py-b .

**Comment by linogaliana** [comment]
Pardon j'avais oublié ce *thread*. J'entends tout à fait vos arguments
