### ISSUE TITLE
échec builds Windows (Pandoc ?)

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/DoReMIFaSol#50]
Le _check_ ne passe plus sous Windows depuis que j'ai ajouté la vignette. :disappointed: 

L'erreur semble venir de Pandoc :

```
* creating vignettes ... ERROR

--- re-building 'donnees_dispo.Rmd' using rmarkdown

Warning in engine$weave(file, quiet = quiet, encoding = enc) :

  Pandoc (>= 1.12.3) not available. Falling back to R Markdown v1.

Quitting from lines 11-12 (donnees_dispo.Rmd) 
```

Ça passe en revanche sur Ubuntu et sur mon poste Windows (où j'ai Pandoc ‘2.9.2’).

**Comment by RLesur** [comment]
Comment fais-tu le check? En ligne de commande ? Dans RStudio ?

**Comment by py-b** [comment]
Je me suis mal exprimé, il s'agit du check de la CI : https://github.com/InseeFrLab/DoReMIFaSol/runs/2371346271

**Comment by pierre-lamarche** [comment]
Oui disons que ce n'est pas gravissime dans la mesure où le CI se fait bien pour le reste des runners. Peut-être tester l'installation de Pandoc 2.9.2 sur les images Windows ?

**Comment by py-b** [comment]
Effectivement, c'est pas bloquant, mais cette petite croix rouge a tendance à m'irriter les yeux. :eyes:

**Comment by pierre-lamarche** [comment]
https://pandoc.org/installing.html#windows
Je vais tester, je me demande si l'utilitaire `chocolatey` est installé sur les serveurs Windows.

**Comment by pierre-lamarche** [comment]
Ca a l'air de passer maintenant sous Windows, même si tout n'est pas encore parfait (mais j'ai l'impression que c'est surtout le requêtage de l'API Sirene qui passe mal sur les checks) : https://github.com/InseeFrLab/DoReMIFaSol/runs/2427183471
Je te propose de clore l'issue.
