### ISSUE TITLE
ajouter la source dans l'objet R

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/DoReMIFaSol#51]
Pour assurer une traçabilité des données, ajouter dans l'objet R les attributs suivants ?

```r
attr(res, "source") <- "Institut National de la Statistique et des Études Économiques (Insee)"
attr(res, "url") <- "https://www.insee.fr/fr/statistiques/<id>" # spécifique à chaque fichier
attr(res, "conditions_utilisation") <- "https://www.insee.fr/fr/information/1300614"
```

Pour le dernier lien, j'ai cherché rapidement, peut-être y a-t-il mieux ailleurs sur le site ?
D'autres idées ? Je pensais pas exemple aux règles de confidentialité, mais c'est variable en fonction des sources.

**Comment by pierre-lamarche** [comment]
Tu veux dire créer une classe `insee.data.frame` qui hériterait de la classe `data.frame` avec les attributs supplémentaires que tu décris ci-dessus ? Ça me semble une excellente idée.

**Comment by py-b** [comment]
Non, pas besoin de forcément modifier la classe (parce qu'on ne va pas ajouter de méthodes particulières a priori).

Je pensais juste ajouter ces attributs tels quels.

(on peut aussi les rassembler dans une liste :)
```r
attr(res, "source") <-
  list(
    producteur = "Institut National de la Statistique et des Études Économiques (Insee)",
    url = "https://www.insee.fr/fr/statistiques/<id>",
    conditions_utilisation = "https://www.insee.fr/fr/information/1300614"
  )
```

**Comment by pierre-lamarche** [comment]
Ok tu parles de quel objet `res` du coup ? Celui auquel je pense est en sortie de la fonction `chargerDonnees`, et il s'agit bien d'une `data.frame`.

**Comment by py-b** [comment]
Oui oui, je parle bien de l'objet final reçu par l'utilisateur. On lui laisse juste sa _class_ de data.frame.

On obtiendrait quelque chose de ce style :
```
'data.frame':	1060614 obs. of  7 variables:
 $ REG     : chr  "84" "84" "84" "84" ...
 $ DEP     : chr  "01" "01" "01" "01" ...
 $ DEPCOM  : chr  "01001" "01001" "01001" "01001" ...
 $ DCIRIS  : chr  "01001" "01001" "01001" "01001" ...
 $ AN      : chr  "2019" "2019" "2019" "2019" ...
 $ TYPEQU  : chr  "A401" "A404" "A405" "A504" ...
 $ NB_EQUIP: num  2 4 2 1 1 1 1 1 1 1 ...
 - attr(*, "spec")=
  .. cols(
  ..   REG = col_character(),
  ..   DEP = col_character(),
  ..   DEPCOM = col_character(),
  ..   DCIRIS = col_character(),
  ..   AN = col_character(),
  ..   TYPEQU = col_character(),
  ..   NB_EQUIP = col_number()
  .. )
 - attr(*, "source")=List of 3
  ..$ producteur            : chr "Institut National de la Statistique et des Études Économiques (Insee)"
  ..$ url                   : chr "https://www.insee.fr/fr/statistiques/3568629"
  ..$ conditions_utilisation: chr "https://www.insee.fr/fr/information/1300614"
```

**Comment by pierre-lamarche** [comment]
Ça ne vaudrait pas le coup de modifier la méthode `print` pour faire apparaître ces attributs de manière explicite (si j'ose dire) ?

**Comment by py-b** [comment]
Bonne idée, je n'y avais pas pensé.

**Comment by py-b** [comment]
@pierre-lamarche : j'étais sur le point de faire une PR, tu as déjà commencé à coder ça ?

**Comment by pierre-lamarche** [comment]
Je t'en prie (d'ailleurs tu peux pusher directement sur le dépôt, tu as les droits pour ça) !

**Comment by py-b** [comment]
> (d'ailleurs tu peux pusher directement sur le dépôt, tu as les droits pour ça) !

(j'aime bien utiliser parfois les PR pour voir les commits liés entre eux ou pour faire tester une idée)
