### ISSUE TITLE
Siret des prédécesseurs et des successeurs (API)

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/DoReMIFaSol#55]
Suite aux échanges par mail avec Guillaume G. de Nantes, je me demande si on ne pourrait pas intégrer facilement le requêtage sur les liens de succesion d'un Siret, il faudrait ajouter une entrée au json des sources :

```json
    {
        "nom": "SIRENE_SIRET_LIENS",
        "libelle": "Données du répertoire Sirène depuis 1973, liens de succession établissement",
        "collection": "SIRENE",
        "lien": "https://api.insee.fr/entreprises/sirene/siret/liensSuccession",
        "type": "json",
        "zip": false,
        "big_zip": false,
        "api_rest": true
    }
```

et adapter l'import dans R des fichiers json.

Peut-être c'est moins simple que ça n'en a l'air ?

**Comment by pierre-lamarche** [comment]
Non, tu as vu juste, _it's that simple_ !

**Comment by py-b** [comment]
J'étais justement en train de regarder ça, magnifique synchro.

**Comment by py-b** [comment]
Effectivement, plutôt simple à intégrer, signe que le code était bien pensé à la base. :+1:

**Comment by RLesur** [comment]
Trop cool ! Ça confirme mon intuition première 😉
`doremifasol` va gagner des utilisateurs 🙂
Un joli exemple de collaboration/mutualisation. Merci @py-b !
