### ISSUE TITLE
Nombre de requêtes max par minutes

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/DoReMIFaSol#57]
Selon le type de compte sur api.insee.fr, il y aurait 2 cadences max de requêtes :

- 30 requêtes par min max
- 500 requêtes par min max

Intégrer ce paramètre dans le package ?

**Comment by py-b** [comment]
Sans objet pour l'instant car pas de fonction faisant plusieurs requêtes.

**Comment by py-b** [comment]
(en fait il y en a mais c'est géré par une temporisation de 10 s si le code 429 - too many requests - survient)

**Comment by pierre-lamarche** [comment]
Oui tu refait une tentative toutes les 10 secondes pour voir si tu peux télécharger de nouveau ou pas. Du coup, le nombre de requêtes est gérée de manière automatique.
