### ISSUE TITLE
Requête API 404

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/DoReMIFaSol#58]
Gérer les cas où la requête ne renvoie aucun résultat (code 404).

Exemple :
```r
telechargerDonnees(
  "SIRENE_SIRET_LIENS",
  argsApi = list(q = "siretEtablissementPredecesseur:32957439600019")
)
```

**Comment by py-b** [comment]
Merci @pierre-lamarche pour la correction.

Le code 404 n'est en revanche pas forcément un erreur nécessitant "stop". Dans l'exemple que je mentionne, la requête est valide, il n'y a simplement pas de liens de succession.

**Comment by pierre-lamarche** [comment]
Normalement là c'est plus propre.
Je me dis qu'il faudra peut-être qu'on envisage de faire du error handling de manière plus formalisée.
