### ISSUE TITLE
Erreur 429 sur requête retournant une seule page

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/DoReMIFaSol#61]
Il se peut que le nombre de requêtes de l'application soit proche de la limite autorisée avant l'appel à `telechargerFichier`.  Dans ce cas, même si la requête ne retourne qu'une seule page de résultats, le programme peut planter.

Un message d'erreur `objet de type 'externalptr' non indiçable` peut être un indice d'une erreur 429 (too many requests) qui n'a pas été gérée correctement. 

On peut simuler ce comportement en utilisant `sirets_successeurs` sur un grand nombre de sirets :
```r
sirets_successeurs(as.character(0:2040))
```
_2040 = 30 requêtes par min pour un compte lambda * 68 sirets par groupe dans sirets_successeurs_

**Comment by pierre-lamarche** [comment]
My bad, ça n'a pas résolu le problème.

**Comment by pierre-lamarche** [comment]
Résolu [ici](https://github.com/InseeFrLab/DoReMIFaSol/commit/2c65389e0e5002269439735f410ec348589a31a7)
