### ISSUE TITLE
Question sur l'emboitement des fonctions de téléchargement dans doremifasol

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/DoReMIFaSol#64]
Je commence à réfléchir à l'implémentation en `python` 🐍  de votre approche

J'ai donc une question pour être sûr de pas rater un éléments dans votre approche:

* La liste des données est disponible dans un [fichier JSON](https://github.com/InseeFrLab/DoReMIFaSol/blob/master/data-raw/liste_donnees.json). C'est super d'avoir ce registre, je pense pouvoir l'utiliser direct en python (où la manipulaion des `json` est bien mieux faite qu'en `R`).
* Vous transformez ça en rda (je me passerai de cette étape en python)
* Vous avez des fonctions dans [`utile.R`](R/utile.R) pour récupérer les infos voulues (url, md5...)
* Vous utilisez  [`telechargerFichier `](R/telechargerFichier.R) et proposez une fonction haut niveau `telechargerDonnees` pour les utilisateurs

Je ne manque pas une étape importante ?

**Comment by pierre-lamarche** [comment]
Génial, excellente idée, je veux bien contribuer si j'ai un peu de temps.
Sur tes questions, @linogaliana : 

- la liste des données se présente effectivement comme un fichier json, qu'on importe sous forme de liste en `R` - avec Python, on sera naturellement sur du dictionnaire avec le module `json` j'imagine, et je suis d'accord avec toi que ça devrait être nettement plus clair ;
- on transforme la liste en `data.frame` pour un ensemble de variables-coeur (variables qui sont renseignées quelle que soit la source de données) - inutile en Python de passer par `pandas` ;
- on a décomposé en deux parties la fonction de chargement des données. On a d'abord `telechargerFichier` qui s'occupe de télécharger les données sous format brut depuis le site, et renvoie une liste avec les paramètres d'import, puis `chargerDonnees` qui va utiliser la liste de paramètres pour faire l'import. La fonction `telechargerDonnees` rend transparente ces opérations.
- on a d'autres fonctions support dont on pourra parler à l'occasion.
Un point d'attention : j'aimerais assez déployer le json sous une url, histoire de rendre le truc plus flexible (et faciliter une mise à jour à la volée sans passer par une mise à jour du package). L'idée c'est : 
robot qui alimente une base de données qui elle-même permet d'alimenter la page de mise à disposition de manière régulière (je m'étais dit au départ qu'on pourrait carrément déployer un service type API, mais c'est overkill pour le moment - sauf à internaliser dans l'API la fonction de recherche de la bonne source).

**Comment by linogaliana** [comment]
> Un point d'attention : j'aimerais assez déployer le json sous une url, histoire de rendre le truc plus flexible (et faciliter une mise à jour à la volée sans passer par une mise à jour du package). L'idée c'est :
robot qui alimente une base de données qui elle-même permet d'alimenter la page de mise à disposition de manière régulière (je m'étais dit au départ qu'on pourrait carrément déployer un service type API, mais c'est overkill pour le moment - sauf à internaliser dans l'API la fonction de recherche de la bonne source).

Ah oui c'est une super idée.

J'avais dans l'idée de faire un test tournant à intervalle régulier (toutes les semaines ?) pour checker toutes les URL du fichier JSON (par exemple s'assurer que `request` renvoie bien un status code 200 pour toutes les clés). Je pense qu'avec python ce sera pas très compliqué une fois développées les fonctions analogues à celles de `doremifasol`

**Comment by linogaliana** [comment]
@pierre-lamarche premiers éléments [ici](https://github.com/InseeFrLab/Py-Insee-Data/pull/19). On peut reporter la suite des remarques dans la *pull request*
