### ISSUE TITLE
Erreur après exécution de telechargerDonnees()

### ISSUE THREAD

**Issue by thierryzorn** [InseeFrLab/DoReMIFaSol#68]
Après lancement de la commande ci-après, message généré, avec erreur : 

*Sélection automatique des données les plus récentes (date = 2017).
Downloading: 390 MB     Aucun répertoire d'importation n'est défini. Les données ont été téléchargées par défaut dans le dossier: C:\Users\THIERR~1.ZOR\AppData\Local\Temp\Rtmps5kdYz
Warning in system2(unzip, args, stdout = NULL, stderr = NULL, invisible = TRUE) :
  '"unzip"' not found
Error in chargerDonnees(telechargerFichier(donnees, date, telDir, argsApi,  : 
  Le fichier de données est introuvable.*

Le fichier *RP2017_LOGEMT_csv.zip* a bien été téléchargé dans mon *tempdir()*, mais le *unzip* a échoué.

Cause probable, le ZIP contient 2 fichiers : le CSV des données et le CSV des metadonnées

Ligne lancée : 
```r
donnees_rp <- telechargerDonnees("RP_LOGEMENT", date = "dernier",
                                 vars = c("COMMUNE", "IPONDL", "CATL"))
```

Version de {doremifasol} : 0.5.1

**Comment by pierre-lamarche** [comment]
Merci pour le retour, la présence des données et des métadonnées est correctement gérée.
L'erreur provient très vraisemblablement du fait que le système ne reconnaît pas la commande `unzip`. Pour entrer dans le détail, s'agissant des fichiers détails à "grosse" volumétrie, le package doit employer une méthode dépendante de l'environnement de l'utilisateur pour dézipper les fichiers téléchargés. Pour dézipper les fichiers, de manière générale, on utilise la commande R `unzip`, qui par défaut fait appel à un processus _standalone_ (`unzip="internal"`), _cf_. la [documentation de la fonction. Mais s'agissant des gros volumes, la section _Note_ est explicite : 
"_The default internal method is a minimal implementation, principally designed for Windows' users to be able to unpack Windows binary packages without external software. It does not (for example) support Unicode filenames as introduced in zip 3.0: for that use unzip = "unzip" with unzip 6.00 or later. It does have some support for bzip2 compression and > 2GB zip files (but not >= 4GB files pre-compression contained in a zip file: like many builds of unzip it may truncate these, in R's case with a warning if possible)._"
`doremifasol` fait donc automatiquement appel à la fonction `unzip` avec le paramètre `unzip = "unzip"` pour tous les gros fichiers, repérés par la variable `big_zip = TRUE` dans les métadonnées de `doremifasol` (le code est [ici](https://github.com/InseeFrLab/DoReMIFaSol/blob/2c520766eb3b3307c30b42797ff7eb9c2c964cd4/R/chargerDonnees.R#L39)).
**Conclusion** : il faut vérifier que la commande `unzip` est installée sur le poste de l'utilisateur. En Windows (l'OS que vous utilisez _a priori_), cela requiert d'avoir installé unZip et d'avoir configuré correctement la variable d'environnement %PATH%.

**Comment by thierryzorn** [comment]
bonjour, merci pour ta réponse,
je suis bien sur Wind'os, snif !
j'ai la commande unzip dans le terminal Cygwin, mais pas dans le  DOS, et je suppose que c'est dans cette dernière qu'il va rechercher unzip. 
Il n'est pas installé a priori,j'ai fait une recherche élargie dans mon C:\
En cherchant sur le net, je trouve un , mais c'est un shareware... 
Un tuyau pour installer un "bon" unzip ? Pour le PATH, je saurai faire ensuite...
PS : Sous Lx, à la maison, ça passe très bien par contre.

**Comment by thierryzorn** [comment]
Re-bonjour,
il y a une version de 'unzip' dans le répertoire de git, installé (chez moi) dans \AppData\Local\Programs\Git\usr\bin
J'ai ajouté le chemin, redémarré un coup, et tout fonctionne !
Mon message dépannera peut-être  d'autres collègues.
En tout cas, merci et longue vie à {DoReMIFaSol}

**Comment by py-b** [comment]
Mentionner cette subtilité dans l'aide de `telechargerDonnees` ?

**Comment by pierre-lamarche** [comment]
Oui je pense que ça peut être utile en effet.

**Comment by py-b** [comment]
Documenté dans ae125d9.
