### ISSUE TITLE
Comment consultez les variables des bases de données ?

### ISSUE THREAD

**Issue by ddotta** [InseeFrLab/DoReMIFaSol#71]
Dans les exemples donnés sur la fonction `telechargerDonnees()` :

```
# fichiers sur insee.fr
bpe_ens_2019 <- telechargerDonnees(donnees = "BPE_ENS")
rp_log <- telechargerDonnees("RP_LOGEMENT", date = "2016", vars = c("COMMUNE", "IPONDL", "CATL"))

```

... il serait pratique de pouvoir consulter le plus facilement possible les variables présentes dans les bases.
Après un petit tour de la documentation mise à disposition sur insee.fr, je me rends compte que les dictionnaires de variables sont en général stockés dans des fichiers pdf joints aux pagex html ce qui doit rendre leur récupération très pénible.

J'ai pensé à modifier [cette ligne](https://github.com/InseeFrLab/DoReMIFaSol/blob/master/R/donnees_dispo.R#L38) pour ajouter une colonne dans le tableau renvoyé par donnees_dispo() ?
Néanmoins dans le json je me rends compte que l'élément `label_col` n'est pas disponible systématiquement dans tous les cas et que de toutes façons, cela serait moche dans l'affichage de la table avec des listes de variables dans des cellules d'un tableau...

Alors peut-être qu'une piste pour s'affranchir du problème de maintenance des variables et pour avoir un peu plus d'infos dans le tableau du pkgdown, ce serait de rajouter (quand il existe) un lien vers la page du dictionnaire d'Insee.fr

Pour les 2 exemples de la doc, cela a l'air de pouvoir se déduire des liens vers les zip déjà présents dans le fichier json :
Pour la BPE :  
`https://www.insee.fr/fr/statistiques/fichier/3568629/bpe20_ensemble_csv.zip`
deviendrait : 
`https://www.insee.fr/fr/statistiques/3568629?sommaire=3568656#dictionnaire`

Le schéma est le même pour le RP Logement :  
`https://www.insee.fr/fr/statistiques/fichier/4229099/RP2016_LOGEMT_csv.zip`
deviendrait  :
`https://www.insee.fr/fr/statistiques/4229099?sommaire=4171558#dictionnaire`

**Comment by py-b** [comment]
Malheureusement, il n'y a pas l'identifiant du sommaire (`...sommaire=3568656...`) dans le fichier json.  
C'est pour ça que tu as fermé l'issue ?

On pourrait en revanche mettre l'url de la page où se trouve le lien de téléchargement (la même que renvoie la fonction [`consulter`](https://inseefrlab.github.io/DoReMIFaSol/reference/consulter.html)).

**Comment by ddotta** [comment]
Oui en autre, je me suis rendu compte que les urls des pages n'étaient pas normalisées et que ce n'était pas si simple.  
Par exemple :  

`doremifasol::consulter("DECES_2020")` renvoit une erreur 404
ça pointe vers `https://www.insee.fr/fr/statistiques/4190491`
qui n'existe plus...
A remplacer par (je ne sais pas - à vérifier) :  
`https://www.insee.fr/fr/statistiques/1893253`  
ou par :  
`https://www.insee.fr/fr/statistiques/5431034?sommaire=5419788&q=deces`  
Et si c'est ce dernier exemple qui est le bon, l'URL est suffixée par `&q=deces` 😒 

Le lien vers le zip lui est bon : 
`https://www.insee.fr/fr/statistiques/fichier/4190491/Deces_2020.zip`
Même s'il pourrait être remplacer par (encore à vérifier - je ne suis pas un expert d'Insee.fr)
`https://www.insee.fr/fr/statistiques/fichier/1893253/base_deces_2020_csv.zip`
ou  
`https://www.insee.fr/fr/statistiques/fichier/5431034/etatcivil2020_dec2020_csv.zip`

Bref, tout ça pour dire qu'il faudrait peut-être un jour enrichir [les tests sur consulter](https://github.com/InseeFrLab/DoReMIFaSol/blob/master/tests/testthat/test_consulter.R) mais ça demande du temps...

En attendant pour ma curiosité j'ai lancé ce script ce matin (mais c'est long à tourner et cet aprèm je ne suis pas dispo)  
Si c'est intéressant je posterai les résultats de `verif`.

Du coup, je ré-ouvre l'issue... (au moins provisoirement 🤣 

``` r
library(doremifasol)
library(RCurl)

# c'est la fonction consulter de doremifasol mais sans l'ouverture dans le navigateur
consulter <- function(donnees, date = NULL) {
  
  caract <- infosDonnees(donnees, date)
  
  # construit l'url web à partir de l'url du fichier
  url <- sub("fichier/([0-9]+)/.+$", "\\1", caract$lien)
  if (caract$collection == "GEOGRAPHIE") {
    url <- sub("/statistiques/", "/information/", url)
  }
  
  # ouvre dans navigateur
  # utils::browseURL(url)
  
  invisible(url)
  
}

verif <- data.frame(
  nom = liste_donnees$nom,
  annee = ifelse(
    is.na(substr(liste_donnees$date_ref,1,4)),
    "dernier",
    substr(liste_donnees$date_ref,1,4)
  ),
  lien_fichier = liste_donnees$lien,
  # Test pour voir si le fichier existe
  test_fichier = sapply(liste_donnees$lien,RCurl::url.exists),
  lien_page = sapply(liste_donnees$nom,consulter,date=verif$annee),
  # Test pour voir si la page existe
  test_page = sapply(verif$lien_page,RCurl::url.exists),
  row.names = F
)

````

**Comment by ddotta** [comment]
Mais si on arrive à se dépatouiller de tout ça, je suis d'accord que rajouter l'URL de la page de la page qui correspond aux données sur le pkgdown, ce serait très utile !  
Et c'est très facile d'ajouter des hyperlinks directement cliquables dans un datatable !

**Comment by py-b** [comment]
Nous attendons les résultats avec impatience. 🍿

**Comment by ddotta** [comment]
Alors, voilà les résultats :  

- Déjà il y a une petite coquille dans `data-raw/liste_donnees.json` pour l'élément "FILOSOFi_DEC_DEP" que `consulter()` ne trouve pas sans-doute à cause de [ça](https://github.com/InseeFrLab/DoReMIFaSol/blob/master/R/utile.R#L22). ça c'est rien du tout. C'est pour ça que les stats ci-dessous portent sur 1337 lignes (et pas 1338 soit le nombre de lignes de liste_donnees)

- Voici le fichier `verif.csv` [ici](https://minio.lab.sspcloud.fr/damiendotta/doremifasol/verif.csv) en espérant que vous ayez accès au fichier (normalement oui car il est en public)
Quelques stats sur ce fichier : 

``` r
table(verif$test_fichier)
# FALSE  TRUE 
# 8  1329 
table(verif$test_page)
# FALSE  TRUE 
# 6  1331 

verif$nom[verif$test_fichier %in% FALSE]
# [1] "PRENOM_NAT"           "PRENOM_DEP"           "RP_INDREG"            "SIRENE_SIREN"         "SIRENE_SIRET"        
# [6] "SIRENE_SIRET_LIENS"   "SIRENE_SIREN_NONDIFF" "SIRENE_SIRET_NONDIFF"
verif$nom[verif$test_page %in% FALSE]
# [1] "DECES_2020"           "SIRENE_SIREN"         "SIRENE_SIRET"         "SIRENE_SIRET_LIENS"   "SIRENE_SIREN_NONDIFF"
# [6] "SIRENE_SIRET_NONDIFF"
```

**Comment by ddotta** [comment]
Pour les cas restants où l'URL n'aboutit pas, je vous laisse décider de ce qu'il faut faire.  
Si besoin, je pourrais un peu aider la semaine prochaine !

**Comment by py-b** [comment]
Tout ce qui commence par `SIRENE_` concerne l'API, donc c'est normal de ne pas avoir de page ou fichier associé.

Je vais regarder les cas restants.

**Comment by py-b** [comment]
Pas de problème pour `RP_INDREG`, selon moi.

Pour les `PRENOM_`, l'url de la page reste la même, mais les noms des fichiers ont changé : 2020 au lieu de 2019. S'attendre à un changement de ce type tous les ans.

Pour `DECES_2020`, le fichier est toujours téléchargeable mais je n'ai pas retrouvé la page où était désormais le lien vers ce fichier (s'il y en a encore une). :thinking:

**Comment by ddotta** [comment]
- Top pour `PRENOM_` !  

- Pour `RP_INDREG` je viens de retester : **ça fonctionne sur mon poste mais pas sur le SSP Cloud**.
Sur le SSP Cloud, j'ai une erreur liée au timeout (le fichier fait 670 Mo en même temps)  que ce soit avec :
``` r
> telechargerDonnees("RP_INDREG",date=2017)
Aucun répertoire d'importation n'est défini. Les données utilisées sont stockées dans le dossier: /tmp/Rtmps485Oa
Les données doivent être mises à jour.
trying URL 'https://www.insee.fr/fr/statistiques/fichier/4507685/RP2017_indreg_csv.zip'
downloaded 129.6 MB

Error in download.file(url = caract$lien, destfile = nomFichier) : 
  download from 'https://www.insee.fr/fr/statistiques/fichier/4507685/RP2017_indreg_csv.zip' failed
In addition: Warning message:
In download.file(url = caract$lien, destfile = nomFichier) :
  URL 'https://www.insee.fr/fr/statistiques/fichier/4507685/RP2017_indreg_csv.zip': Timeout of 60 seconds was reached
```
ou même simplement :
```
> download.file("https://www.insee.fr/fr/statistiques/fichier/4507685/RP2017_indreg_csv.zip",
+               destfile = paste0(tempdir(),"/output.zip"))
trying URL 'https://www.insee.fr/fr/statistiques/fichier/4507685/RP2017_indreg_csv.zip'
downloaded 148.3 MB

Error in download.file("https://www.insee.fr/fr/statistiques/fichier/4507685/RP2017_indreg_csv.zip",  : 
  download from 'https://www.insee.fr/fr/statistiques/fichier/4507685/RP2017_indreg_csv.zip' failed
In addition: Warning message:
In download.file("https://www.insee.fr/fr/statistiques/fichier/4507685/RP2017_indreg_csv.zip",  :
  URL 'https://www.insee.fr/fr/statistiques/fichier/4507685/RP2017_indreg_csv.zip': Timeout of 60 seconds was reached
```
Et comme j'ai lancé le script de test qui crée `verif` depuis le SSP Cloud, ça peut peut-être expliquer pourquoi j'ai récupéré un `FALSE` sur ce fichier

- Et pour `DECES_2020` je suis comme toi, pas trouvé de page associée au fichier.

**Comment by ddotta** [comment]
Du coup, en résumé, y a plus qu'à trouver une solution pour `DECES_2020` avant de pouvoir faire ça (enfin si vous voulez) :

> On pourrait en revanche mettre l'url de la page où se trouve le lien de téléchargement

**Comment by ddotta** [comment]
La page correspondante au fichier `DECES_2020` est [celle-là](https://www.insee.fr/fr/information/4190491) car on arrive bien sur le même fichier.  
Donc je crois qu'il y a juste à changer dans l'URL le `statistiques` par le `information`

**Comment by py-b** [comment]
Super contributions, @ddotta. :rocket:  
On a bien fait de réouvrir l'issue.

**Comment by ddotta** [comment]
Cool ! Merci pour la review @py-b !
