### ISSUE TITLE
Mise à jour des données du recensement

### ISSUE THREAD

**Issue by sylvaine31** [InseeFrLab/DoReMIFaSol#85]
Bonjour, 
Je remarque que DoReMiFaSol n'est pas du tout à jour sur les données du recensement de la population (derniers millésimes : 2017) pour les fichiers détails. Est-ce envisageable de mettre les derniers millésimes disponibles ?

https://www.insee.fr/fr/statistiques/6544333?sommaire=6456104

Merci, 

Sylvaine

**Comment by py-b** [comment]
Bonjour @sylvaine31 
Effectivement, on va faire ce qu'il faut pour combler le retard.

**Comment by py-b** [comment]
Données 2018, 2019 et 2020 ajoutées.
